import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/context/QueryProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-full font-sans antialiased">
        <main className="flex min-h-screen flex-col p-2 h-full bg-violet-100">
          <AuthProvider>
            <QueryProvider>
            {children}
            </QueryProvider>
          </AuthProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
